module master_project

include("data_navierstokes_FVM.jl")
include("stochastic_interpolant.jl")
include("u-net_conv_cond_attention.jl")
include("train.jl")
include("generate_closure.jl")
include("evaluation.jl")
include("inference.jl")

export step_rk4
export face_average_syver
export face_average_syver!
export compute_mean_std
export standardize_training_set_per_channel
export standardize_trajectories

export inverse_standardize_set_per_channel
export save_large_bson
export load_large_bson
export generate_or_load_data
export generate_or_load_stand_data
export compute_velocity_magnitude
export plot_velocity_magnitudes
export create_training_sets
export split_trajectories

export stochastic_interpolant
export time_derivative_stochastic_interpolant
export alpha
export beta
export sigma
export derivative_alpha
export derivative_beta
export derivative_sigma

export periodic_padding_gpu
export ConvPeriodicLayer
export SelfAttentionBlock
export sinusoidal_embedding
export ConvNextBlock_down
export ConvNextBlock_up
export BottomLayerWithAttention
export UNet
export build_full_unet

export initialize_or_load_model
export load_model
export train!
export get_minibatch_NS
export loss_fn
export save_model
export save_training_state
export load_training_state

export generate_closure
export diffusion
export score
export euler_maruyama
export heuns_method
# export step_rk4_with_closure

export compute_metrics_average
export mean_squared_error
export relative_root_mse
export plot_closure_prediction
export time_steps_dependency

export inference
export batched_inference

export animation_LES_model_truth
export error_comparison_LES_model
export snapshot_comparison
export compute_energy_spectra
export compute_total_energy
export compute_enstrophy_spectra
export compute_total_enstrophy
export plot_total_energy_over_time
export plot_total_enstrophy_over_time

end

